language: java
before_install:
  - wget https://raw.github.com/bootstraponline/livepreview_test/master/from_chrome/xvfb/Xvfb.32bit -O /tmp/Xvfb
  - chmod +x /tmp/Xvfb
  - /tmp/Xvfb :9 -screen 0 1024x768x24 -ac 2>/dev/null &
  - export DISPLAY=:9
  - sudo apt-get install -y libxss1 libnss3-1d xdg-utils > /dev/null 2>&1
  - URL='https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb'; FILE=`mktemp`; wget "$URL" -qO $FILE && sudo dpkg -i $FILE > /dev/null 2>&1; rm $FILE